name: RDP with Ngrok

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ngrok RDP
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
        run: |
          powershell -ExecutionPolicy Bypass -File .\configure.ps1 -ngrokAuthToken $env:NGROK_AUTH_TOKEN -rdpPassword $env:RDP_PASSWORD

      - name: Wait for Ngrok to establish tunnel
        run: |
          sleep 10  # Tunggu beberapa detik untuk memastikan ngrok siap
